### ISSUE TITLE
数据形式

### ISSUE THREAD

**Issue by exitxingling** [WenmuZhou/mxnet_cifar10#1]
请问作者，您这个数据是什么形式存储的啊？

**Comment by WenmuZhou** [comment]
在一个文件里，label.txt    文件里是img_path label

**Comment by exitxingling** [comment]
数据处理模块是要把CIFAR10的1，2，3，4，5个batch的训练数据都处理好之后放到一个train文件夹里面吗？

**Comment by WenmuZhou** [comment]
数据是这样的，要有一个 train和test文件夹  train文件夹里的每一个文件夹都存放的一类的图片

**Comment by exitxingling** [comment]
这个怎么处理啊，能分享一下吗？我看其他很多种处理方式，不知道您这个具体是怎么处理的。

**Comment by WenmuZhou** [comment]
你看一下这个的源码ImageFolderDataset

**Comment by exitxingling** [comment]
我的意思是说您的数据，从CIFAR10官网上下载下来之后，将train和test的数据都按类别归类之后，才能运行吗？我是想问这个归类的具体是怎么处理的

**Comment by WenmuZhou** [comment]
直接拷贝的

**Comment by exitxingling** [comment]
啊，，，，那好吧。。。。
